const API_BASE = 'https://api.noopschallenge.com';

function start() {

  var can = document.createElement('canvas');
  can.id = 'canvas'
  document.getElementById('main').appendChild(can);
  var canvas = document.getElementById('canvas');
  var lastColor = call_noop('#6432a8').colors[0].value;

  // create a new circle every 1500 ms with a slightly varying color from the last
  var create = function() {
    var randomColor = call_noop(lastColor).colors[0].value;
    new_circle(canvas, randomColor);
    lastColor = randomColor;
    setTimeout(create, 1500);
  }

  create();
}

function new_circle(canvas, randomColor) {

  var ctx = canvas.getContext('2d');
  ctx.fillStyle = randomColor;

  var fn = function(i) {
    ctx.beginPath();
    ctx.arc(canvas.width/2, canvas.height/2, i, 0, 2 * Math.PI);
    ctx.fill();  
    ctx.stroke();
    i++;
    if(i < 2*canvas.width/3) {
        setTimeout(fn, 10, i + 1);
    }
  }
  // call recursive function which draws circle with incremental radius until screen is filled
  fn(0);
}

function call_noop(prev){

  // break up the hex color passed into RBG, dropping the #
  red = to_dec(prev.slice(1,3));
  blue = to_dec(prev.slice(3,5));
  green = to_dec(prev.slice(5,7));

  // ensure adding randomness of [-10, 10] to values won't produce values outside min max hex values
  if (red < 10) {
      red = 10;
  }
  else if (red > 245) {
    red = 245;
  }
  if (green < 8) {
    green = 8;
  }
  else if (green > 247) {
    green = 245;
  } 

  if (blue < 10) {
    blue = 10;
  }
  else if (blue > 245) {
  blue = 247;
  }

  // create slight variations of previous color generated by adding a random value -11<x<11 to red, blue, green
  left = ''.concat((red+random_variation()).toString(16),(blue+random_variation()).toString(16),(green+random_variation()).toString(16));
  //right = ''.concat((red+random_variation()).toString(16),(blue+random_variation()).toString(16),(green+random_variation()).toString(16));
  last = prev.slice(1)

  // use seed endpoint to create combinations of passed hex values to add continual slight variation to color
  let url = API_BASE.concat('/hexbot?seed=', left, ',', last)//, ',', right)
  console.log(url)

  var mydata;
  $.ajax({
    async: false,
    url: url,
    success: function(data) {
      mydata = data;
    }
  });

  console.log(mydata);
  return mydata
}

function random_variation(color) {
  // create a random value between 1 and 10, randomly assign + or -

  var value = Math.floor((Math.random() * 10) + 1) +10;
  var plusOrMinus = Math.random() < 0.5 ? -1 : 1;

  return plusOrMinus*value
}


function to_dec (hex) {
  return parseInt(hex, 16);
}

window.onload = function (event) {
  start();
};